FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt --no-cache-dir

# No need to EXPOSE a specific port, Cloud Run will provide the PORT environment variable
# EXPOSE 3000

ENV PYTHONPATH /app

# Modify the CMD to use the PORT environment variable
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
